module.exports = {
    ERROR_CREATING_ACCOUNTTRANSACTION: "Could'nt Create accounttransaction",
    ERROR_GETTING_ACCOUNTTRANSACTION: "Couldn't Get accounttransaction",
    ERROR_GETTING_ACCOUNTTRANSACTIONS: "Can't Fetch All accounttransactions",

    ACCOUNT_TRANSACTION_TYPE : {
        ACCOUNT_CREATED: 'ACCOUNT_CREATED',
        SALE: 'SALE',
        SALE_RETURN: 'SALE RETURN',
        SALE_PAYMENT: 'SALE_PAYMENT',
        BOOKING: 'BOOKING',
        PURCHASE: 'PURCHASE',
        EXPENSE: 'EXPENSE',
        RECOVERY_GIVEN: 'RECOVERY_GIVEN',
        RECOVERY_TAKEN: 'RECOVERY_TAKEN',
        TRANSFER: 'TRANSFER',
        LOAN_GIVEN:'LOAN_GIVEN',
        LOAN_TAKEN:'LOAN_TAKEN',
        INCENTIVE: 'INCENTIVE',
        BANK_PROFIT: 'BANK_PROFIT',
        CAPITAL_ADDED: 'CAPITAL_ADDED',
        CAPITAL_WITHDRAWN: 'CAPITAL_WITHDRAWN',
        PROFIT_POSTED: 'PROFIT_POSTED',
        STOCK_RETURN: 'STOCK_RETURN',
        MANUAL_STOCK_RETURN: 'MANUAL STOCK_RETURN'
    },
}