module.exports = {
    //Sales
    SALE_CREATED: 'SALE CREATED',
    ERROR_GETTING_SALE: 'ERROR GETTING SALE',
    ERROR_RETURNING_SALE_ITEMS: 'ERROR RETURNIN SALE ITEMS',
    ERROR_CREATING_SALE_PAYMENT: 'ERROR CREATING SALE PAYMENT',
    ERROR_GETTING_SALE_PAYMENTS: 'ERROR GETTING SALE PAYMENTS',
}