module.exports = {
    STOCK_BOOK_ADDED: 'STOCK BOOK ENTRY ADDED',
    ERROR_CREATING_STOCK_BOOK: 'ERROR CREATING STOCK BOOK',
    COULDNT_ADD_STOCO_BOOK: 'COULDNT  ADD STOCK BOOK ENTRY',
    ERROR_GETTING_STOCK_BOOK: 'ERROR GETTING STOCK BOOK',

    TYPE : {
        MANUAL_STOCK: 'MANUAL STOCK',
        PURCHASE_STOCK: 'PURCHASE STOCK',
        SALE: 'SALE',
        STOCK_RETURN: 'STOCK RETURN',
        MANUAL_STOCK_RETURN: 'MANUAL STOCK RETURN',
    }
}