const app = require('..');
const dashboardController = require('../controllers/dashboard.controller');
app.get('/dashboard/topbar',dashboardController.getTopBarData);
app.get('/dashboard/businessreport',dashboardController.getBusinessReport);
app.get('/dashboard/toploans',dashboardController.getTopLoans);
app.get('/dashboard/topSellingProductsThisMonth',dashboardController.getTopSellingProductsThisMonth);
app.get('/dashboard/topSellingProductsAllTime',dashboardController.getTopSellingProductsAllTime);
app.get('/dashboard/topCustomersAllTime',dashboardController.getTopCustomersAllTime);
app.get('/dashboard/topProfitableProducts',dashboardController.getTopProfitableProducts);
app.get('/dashboard/mostReturnedProducts',dashboardController.getMostReturnedProducts);
app.get('/dashboard/mostProfitableCompaniesByPercentage',dashboardController.getMostProfitableCompaniesByPercentage);
